// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alcccdaqebncfmlhzuae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsY2NjZGFxZWJuY2ZtbGh6dWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDI1MDMsImV4cCI6MjA3NDQ3ODUwM30.cP3y8v9Ru9aGvdX0mLxlbTmro4rVk6pu2uE8-j0wLGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});